In [24]:
import numpy as np
from numpy import column_stack, sign
from numpy.linalg import inv, matrix_rank
import matplotlib.pyplot as plt
from check_inverse import check_inverse_rank
from sklearn.preprocessing import PolynomialFeatures

def bin_class(X,y,X_new,poly, degree, lmbd, mod):

    poly = PolynomialFeatures(degree)
    P = poly.fit_transform(X)
    P_new = poly.fit_transform(X_new)
    print(f"P with shape {P.shape}:")
    print(P)
    print(f"Pnew with shape {P_new.shape}:")
    print(P_new)

    # check for exact soln
    rank_X = matrix_rank(X)
    rank_Xy = matrix_rank(column_stack([X, y]))
    if rank_X == rank_Xy: print("has exact soln")
    else: print("no exact soln, use least sq soln")

    if (check_inverse_rank(P.T @ P)):
        # compute the optimal weights
        w_poly = inv(P.T @ P) @ P.T @ y
        print(f"w: {w_poly}")
    
        # find ytr_pred
        ytr_pred = P @ w_poly
        print(f"ytr_pred: {ytr_pred}")
        
        # classify ytr_pred
        ytr_pred_class = sign(ytr_pred)
        print(f"sign: {ytr_pred_class}") 
        
        # find yts_pred
        yts_pred = P_new @ w_poly
        print(f"yts_pred: {yts_pred}")
        
        # classify yts_pred
        yts_pred_class = sign(yts_pred)
        print(f"sign: {yts_pred_class}") 
    else:
        if mod == "EE2213":
            L2_reg = np.identity(P.shape[1])
            w_poly_ridge = inv(P.T @ P + lmbd * L2_reg) @ P.T @ y # EE2213 ver.
        else:
            L2_reg = np.identity(P.shape[0])
            w_poly_ridge = P.T @ inv(P @ P.T + lmbd * L2_reg) @ y # EE2211 ver.
        
        print(f"w (poly ridge):")
        print(w_poly_ridge)

        # find ytr_pred
        ytr_pred = X @ w_poly_ridge
        print(f"ytr_pred: {ytr_pred}")
        
        # classify ytr_pred
        ytr_pred_class = sign(ytr_pred)
        print(f"sign: {ytr_pred_class}") 
        
        # find yts_pred
        yts_pred = X_new @ w_poly_ridge
        print(f"yts_pred: {yts_pred}")
        
        # classify yts_pred
        yts_pred_class = sign(yts_pred)
        print(f"sign: {yts_pred_class}") 
    


In [25]:
X = np.array([4,7,10,2,3,9]).reshape(-1,1)
# X_bias = np.column_stack([np.ones(X.shape[0]),X])
y = np.array([-1,-1,-1,1,1,1]).reshape(-1,1)
X_new = np.array([[6]])
# X_new_bias = np.column_stack([np.ones(X_new.shape[0]), X_new])

poly = True
degree = 4
lmbd = 0.01
mod = "EE2211"

bin_class(X, y, X_new, poly, degree, lmbd, mod)

P with shape (6, 5):
[[1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02]
 [1.000e+00 7.000e+00 4.900e+01 3.430e+02 2.401e+03]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03 1.000e+04]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01]
 [1.000e+00 9.000e+00 8.100e+01 7.290e+02 6.561e+03]]
Pnew with shape (1, 5):
[[1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03]]
no exact soln, use least sq soln
matrix rank is : 5
matrix size is : (5, 5)
matrix is invertible
w: [[-11.21971831]
 [ 13.52136821]
 [ -4.88054326]
 [  0.65537223]
 [ -0.02923541]]
ytr_pred: [[-0.76338028]
 [-1.11830986]
 [-1.04225352]
 [ 1.07605634]
 [ 0.74647887]
 [ 1.10140845]]
sign: [[-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]]
yts_pred: [[-2.11975855]]
sign: [[-1.]]
