In [14]:
import numpy as np
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder
from check_inverse import check_inverse_rank

def multi_class(X, y, Xnew, use_poly, lambda_ridge, order, mod):
    
    encoder = OneHotEncoder(sparse_output=False)
    ytr_onehot = encoder.fit_transform(y)
    
    print(f"ytr_onehot:")
    print(ytr_onehot)
    
    # poly
    if use_poly:
        poly = PolynomialFeatures(order)
        P = poly.fit_transform(X)
        P_new = poly.fit_transform(Xnew)
        
        print(f"P with shape {P.shape}:")
        print(P)
        print(f"Pnew with shape {P_new.shape}:")
        print(P_new)

        if (check_inverse_rank(P.T @ P)):
            w_poly = inv(P.T @ P) @ P.T @ ytr_onehot
            print(f"w (poly):")
            print(w_poly)
            
            # find ytr_pred
            ytr_pred = P @ w_poly
            print(f"pred_y_train (poly): \n {ytr_pred}")
            
            # classify ytr_pred
            ytr_pred_class = np.argmax(ytr_pred, axis=1) + 1
            print(f"ytr_pred_class (poly):")
            print(ytr_pred_class)
            
            # find yts_pred
            yts_pred = P_new @ w_poly
            print(f"pred_y (poly):\n {yts_pred}")
            
            # classify yts_pred
            yts_pred_class = np.argmax(yts_pred, axis=1) + 1
            print(f"yts_pred_class (poly):")
            print(yts_pred_class)
        
        else:
            if mod == "EE2213":
                L2_reg = np.identity(P.shape[1])
                w_poly_ridge = inv(P.T @ P + lambda_ridge * L2_reg) @ P.T @ ytr_onehot # EE2213 ver.
            else:
                L2_reg = np.identity(P.shape[0])
                w_poly_ridge = P.T @ inv(P @ P.T + lambda_ridge * L2_reg) @ ytr_onehot # EE2211 ver.
            print(f"w (poly ridge):")
            print(w_poly_ridge)
            
            # find ytr_pred
            ytr_pred = P_new @ w_poly_ridge
            print(f"pred_y (poly ridge): {ytr_pred}")
            
            # classify ytr_pred
            ytr_pred_class = np.argmax(ytr_pred, axis=1) + 1
            print(f"ytr_pred_class (poly ridge):")
            print(ytr_pred_class)
            
            # find yts_pred
            yts_pred = P_new @ w_poly_ridge
            print(f"pred_y (poly ridge): {yts_pred}")
            
            # classify yts_pred
            yts_pred_class = np.argmax(yts_pred, axis=1) + 1
            print(f"yts_pred_class (poly ridge):")
            print(yts_pred_class)
    # linear 
    else:
        w = inv(X.T @ X) @ X.T @ ytr_onehot
        print(f"w (linear): {w}")
        
        yts_pred = Xnew @ w
        
        print(f"yts_pred (linear):")
        print(yts_pred)
        
        yts_pred_class = np.argmax(yts_pred, axis=1)
        print(f"yts_pred_class (linear)")
        print(yts_pred_class)
        
        ytr_pred = X @ w
        
        print(f"ytr_pred (linear):")
        print(ytr_pred)
        
        ytr_pred_class = np.argmax(ytr_pred, axis=1)
        print(f"ytr_pred_class (linear)")
        print(ytr_pred_class)


In [ ]:
X = np.array([4,7,10,2,3,9]).reshape(-1,1)
# X = np.column_stack([np.ones(X.shape[0]),X])
y = np.array([-1,-1,-1,1,1,1]).reshape(-1,1)
X_test = np.array([[6]])
# X_test = np.column_stack([np.ones(X_test[0]),X_test])

use_poly = True
lambda_ridge = 1e-6
degree = 4
mod = "EE2211"

multi_class(X, y, X_test, use_poly, lambda_ridge, degree, mod)

ytr_onehot:
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]
P with shape (6, 5):
[[1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02]
 [1.000e+00 7.000e+00 4.900e+01 3.430e+02 2.401e+03]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03 1.000e+04]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01]
 [1.000e+00 9.000e+00 8.100e+01 7.290e+02 6.561e+03]]
Pnew with shape (1, 5):
[[1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03]]
matrix rank is : 5
matrix size is : (5, 5)
matrix is invertible
w (poly):
[[ 6.10985915 -5.10985915]
 [-6.7606841   6.7606841 ]
 [ 2.44027163 -2.44027163]
 [-0.32768612  0.32768612]
 [ 0.01461771 -0.01461771]]
pred_y_train (poly): 
 [[ 0.88169014  0.11830986]
 [ 1.05915493 -0.05915493]
 [ 1.02112676 -0.02112676]
 [-0.03802817  1.03802817]
 [ 0.12676056  0.87323944]
 [-0.05070423  1.05070423]]
ytr_pred_class (poly):
[1 1 1 2 2 2]
pred_y (poly):
 [[ 1.55987928 -0.55987928]]
yts_pred_class (poly):
[1]
