In [ ]:
import numpy as np
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures
from check_inverse import check_inverse_rank
from sklearn.metrics import mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt

def poly_reg(X, y, Xnew, lambda_ridge, order):
    
    ## Generate polynomial features
    poly = PolynomialFeatures(order)
    P = poly.fit_transform(X)
    P_new = poly.fit_transform(Xnew)
    print(f"P with shape {P.shape}:")
    print(P)
    print(f"Pnew with shape {P_new.shape}:")
    print(P_new)

    if (check_inverse_rank(P.T @ P)):
        w_poly = inv(P.T @ P) @ P.T @ y
        print(f"w (poly):\n")
        print(w_poly)
        
        # predict new input
        yts_pred = P_new @ w_poly
        print(f"pred_y (poly): {yts_pred}")
        # find mse(tr)
        ytr_pred = P @ w_poly
        msetr = mean_squared_error(y, ytr_pred)
        print(f"mse (train, poly): {msetr}")
        # find mae(tr)
        maetr = mean_absolute_error(y, ytr_pred)
        print(f"mae (train, poly): {maetr}")
        
        return w_poly, ytr_pred
    else:
        L2_reg = np.identity(P.shape[1])
        w_poly_ridge = inv(P.T @ P + lambda_ridge * L2_reg) @ P.T @ y
        print(f"w (poly ridge):")
        print(w_poly_ridge)

        # predict new input
        yts_pred = P_new @ w_poly_ridge
        print(f"pred_y (poly ridge): {yts_pred}")
        # find mse(tr)
        ytr_pred = P @ w_poly_ridge
        msetr = mean_squared_error(y, ytr_pred)
        print(f"mse (train, poly): {msetr}")
        # find mae(tr)
        maetr = mean_absolute_error(y, ytr_pred)
        print(f"mae (train, poly): {maetr}")

        return w_poly_ridge, ytr_pred

In [76]:
X1 = np.array([[1,4],[5,-1],[2,3]])
X1_bias = np.column_stack([np.ones(X1.shape[0]),X1])
y = np.array([1,3,1]).reshape(-1,1)

X1_new = np.array([[1.5,1]])
X1_new_bias = np.column_stack([np.ones(X1_new.shape[0]),X1_new])

poly_reg(X1, y, X1_new, 0.1, 2)

P with shape (3, 6):
[[ 1.  1.  4.  1.  4. 16.]
 [ 1.  5. -1. 25. -5.  1.]
 [ 1.  2.  3.  4.  6.  9.]]
Pnew with shape (1, 6):
[[1.   1.5  1.   2.25 1.5  1.  ]]
w (poly ridge):
[[0.00802774]
 [0.02666237]
 [0.00941032]
 [0.11272378]
 [0.00025798]
 [0.05085961]]
pred_y (poly ridge): [[0.36230669]]
mse (train, poly): 8.227949273043732e-08
mae (train, poly): 0.0002675913011983555


(array([[0.00802774],
        [0.02666237],
        [0.00941032],
        [0.11272378],
        [0.00025798],
        [0.05085961]]),
 array([[0.99984088],
        [2.9995934 ],
        [0.99976294]]))