In [ ]:

import numpy as np
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures
from check_inverse import check_inverse_rank
from sklearn.metrics import mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt

def poly_reg(X, y, Xnew, lambda_ridge, order, mod):
    
    ## Generate polynomial features
    poly = PolynomialFeatures(order)
    P = poly.fit_transform(X)
    P_new = poly.fit_transform(Xnew)
    
    print(f"P with shape {P.shape}:")
    print(P)
    print(f"Pnew with shape {P_new.shape}:")
    print(P_new)

    if (check_inverse_rank(P.T @ P)):
        w_poly = inv(P.T @ P) @ P.T @ y
        print(f"w (poly):\n")
        print(w_poly)
        
        # find mse(tr)
        ytr_pred = P @ w_poly
        print(f"ytr_pred (poly): {ytr_pred}")
        
        # predict new input
        yts_pred = P_new @ w_poly
        print(f"yts_pred (poly): {yts_pred}")
        
        # find mse(tr)
        msetr = mean_squared_error(y, ytr_pred)
        print(f"msetr (train, poly): {msetr}")
        
        # find mae(tr)
        maetr = mean_absolute_error(y, ytr_pred)
        print(f"maetr (train, poly): {maetr}")
        
        # find mse(te)
        msets = mean_squared_error(y, yts_pred)
        print(f"msets (train, poly): {msets}")
        
        # find mae(te)
        maets = mean_absolute_error(y, yts_pred)
        print(f"maets (train, poly): {maets}")
        
        return w_poly, ytr_pred
    else:
        if mod == "EE2213":
            L2_reg = np.identity(P.shape[1])
            w_poly_ridge = inv(P.T @ P + lambda_ridge * L2_reg) @ P.T @ y # EE2213 ver.
        else:
            L2_reg = np.identity(P.shape[0])
            w_poly_ridge = P.T @ inv(P @ P.T + lambda_ridge * L2_reg) @ y # EE2211 ver.
        
        print(f"w (poly ridge):")
        print(w_poly_ridge)
        
        
        # find mse(tr)
        ytr_pred = P @ w_poly_ridge
        print(f"ytr_pred (poly ridge): {ytr_pred}")
        
        # predict new input
        yts_pred = P_new @ w_poly_ridge
        print(f"yts_pred (poly ridge): {yts_pred}")
        
        # find mse(tr)
        msetr = mean_squared_error(y, ytr_pred)
        print(f"msetr (train, poly ridge): {msetr}")
        
        # find mae(tr)
        maetr = mean_absolute_error(y, ytr_pred)
        print(f"maetr (train, poly ridge): {maetr}")
        
        # find mse(te)
        msets = mean_squared_error(y, yts_pred)
        print(f"msets (train, poly ridge): {msets}")
        
        # find mae(te)
        maets = mean_absolute_error(y, yts_pred)
        print(f"maets (train, poly ridge): {maets}")

        return w_poly_ridge, ytr_pred

In [11]:
X1 = np.array([[1,1],[1,1],[1,1],[1,1]])
# X1_bias = np.column_stack([np.ones(X1.shape[0]),X1])
y = np.array([1,1]).reshape(-1,1)
X1_new = np.array([[1,1]])
# X1_new_bias = np.column_stack([np.ones(X1_new.shape[0]),X1_new])

order = 2
lmbd = 1e-6
mod = "EE2211"

poly_reg(X1, y, X1_new, lmbd, order, mod)

P with shape (4, 6):
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Pnew with shape (1, 6):
[[1. 1. 1. 1. 1. 1.]]
matrix rank is : 1
matrix size is : (6, 6)
matrix is not invertible
no soln found
