In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np
from numpy import column_stack, transpose
from numpy.linalg import inv, matrix_rank
import matplotlib.pyplot as plt
from check_inverse import check_inverse_rank

def linear_reg(X,y,X_new):

    # check for exact soln
    rank_X = matrix_rank(X)
    rank_Xy = matrix_rank(column_stack([X, y]))
    if rank_X == rank_Xy: print("has exact soln")
    else: print("no exact soln, use least sq soln")
    
    if (check_inverse_rank(X.T @ X)):
        # compute weight
        w = inv(transpose(X) @ X) @ transpose(X) @ y
        print(f"w:\n {w}")

        # Predicting for a new input
        yts_pred = X_new @ w
        print(f"pred_y: {yts_pred}")
        
        # find mse(tr)
        ytr_pred = X @ w
        msetr = mean_squared_error(y, ytr_pred)
        print(f"mse (train): {msetr}")

        # mse(te) per pt.
        msets_per_point = (yts_pred - y) ** 2
        print(f"mse per pt:\n {msets_per_point}")
        print(msets_per_point)
    else:
        print("X.T @ Xnot invertible, no soln found")  
        return

In [6]:
X1 = np.array([1.6,1.5,1.0,1.1,1.2,0.9]).reshape(-1,1)
X1_bias = np.column_stack([np.ones(X1.shape[0]),X1])
y = np.array([3.1,3.4,2.9,3.0,3.8,2.9]).reshape(-1,1)

X1_new = np.array([0.5]).reshape(-1,1)
X1_new_bias = np.column_stack([np.ones(X1_new.shape[0]),X1_new])

linear_reg(X1_bias, y, X1_new_bias)

no exact soln, use least sq soln
w:
 [[2.58283262]
 [0.49356223]]
pred_y: [[2.82961373]]
mse (train): 0.08895565092989986
mse per pt:
 [[0.07310873]
 [0.32534049]
 [0.00495423]
 [0.02903148]
 [0.94164951]
 [0.00495423]]
[[0.07310873]
 [0.32534049]
 [0.00495423]
 [0.02903148]
 [0.94164951]
 [0.00495423]]
