In [12]:
import numpy as np
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures
from check_inverse import check_inverse_rank
from sklearn.metrics import mean_squared_error

def poly_reg(X, y, Xnew, lambda_ridge, order):
    
    ## Generate polynomial features
    poly = PolynomialFeatures(order)
    P = poly.fit_transform(X)
    P_new = poly.fit_transform(Xnew)
    print(f"P with shape {P.shape}:")
    print(P)
    print(f"Pnew with shape {P_new.shape}:")
    print(P_new)

    if (check_inverse_rank(P.T @ P)):
        w_poly = inv(P.T @ P) @ P.T @ y
        print(f"w (poly):\n")
        print(w_poly)
        
        # predict new input
        yts_pred = P_new @ w_poly
        print(f"pred_y (poly): {yts_pred}")
        # find mse(tr)
        ytr_pred = P @ w_poly
        msetr = mean_squared_error(y, ytr_pred)
        print(f"mse (train, poly): {msetr}")
    else:
        L2_reg = np.identity(P.shape[1])
        w_poly_ridge = inv(P.T @ P + lambda_ridge * L2_reg) @ P.T @ y
        print(f"w (poly ridge):")
        print(w_poly_ridge)
        
        # predict new input
        yts_pred = P_new @ w_poly_ridge
        print(f"pred_y (poly ridge): {yts_pred}")
        # find mse(tr)
        ytr_pred = P @ w_poly_ridge
        msetr = mean_squared_error(y, ytr_pred)
        print(f"mse (train, poly): {msetr}")


In [13]:
X1 = np.array([1.6,1.5,1.0,1.1,1.2,0.9]).reshape(-1,1)
X1_bias = np.column_stack([np.ones(X1.shape[0]),X1])
y = np.array([3.1,3.4,2.9,3.0,3.8,2.9]).reshape(-1,1)

X1_new = np.array([0.5]).reshape(-1,1)
X1_new_bias = np.column_stack([np.ones(X1_new.shape[0]),X1_new])

poly_reg(X1, y, X1_new, 0.0001, 6)

P with shape (6, 7):
[[ 1.        1.6       2.56      4.096     6.5536   10.48576  16.777216]
 [ 1.        1.5       2.25      3.375     5.0625    7.59375  11.390625]
 [ 1.        1.        1.        1.        1.        1.        1.      ]
 [ 1.        1.1       1.21      1.331     1.4641    1.61051   1.771561]
 [ 1.        1.2       1.44      1.728     2.0736    2.48832   2.985984]
 [ 1.        0.9       0.81      0.729     0.6561    0.59049   0.531441]]
Pnew with shape (1, 7):
[[1.       0.5      0.25     0.125    0.0625   0.03125  0.015625]]
matrix rank is : 6
matrix size is : (7, 7)
matrix is not invertible
w (poly ridge):
[[ 4.64389954]
 [-4.08282768]
 [-1.39058692]
 [ 3.70437887]
 [ 3.23921837]
 [-3.85972618]
 [ 0.74904689]]
pred_y (poly ridge): [[2.81142488]]
mse (train, poly): 0.0330252194045677
